name: coopenergy
description: Coopératives solaires transparentes sur blockchain
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Accès contacts téléphone (Android/iOS uniquement)
  flutter_contacts: ^1.1.9+1

  # Permissions
  permission_handler: ^11.3.1

  # Supabase
  supabase_flutter: ^2.3.4

  # Navigation
  go_router: ^13.2.0

  # State management
  flutter_riverpod: ^2.5.1

  # Blockchain
  web3dart: ^2.7.3
  http: ^1.2.1

  # UI
  google_fonts: ^6.2.1
  fl_chart: ^0.67.0        # graphiques progression
  shimmer: ^3.0.0          # skeleton loading screens

  # Utilitaires
  intl: 0.20.2
  uuid: ^4.3.3
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.1.0

  # PDF export
  pdf: ^3.10.8
  printing: ^5.12.0

  convert: ^3.1.1

  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/fonts/
    - assets/abi/coopenergy.json